apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      # update when code is pushed to a new location
      url: $GITREPO
      ref:
        branch: main

